#include "Ast.h"
#include "SymbolTable.h"
#include "Unit.h"
#include "Instruction.h"
#include "IRBuilder.h"
#include <string>
#include "Type.h"
#include <assert.h>
#include "ArrayUtil.h"
extern FILE *yyout;
int Node::counter = 0;
IRBuilder *Node::builder = nullptr;
int genBr = 0; // 优化用，生成跳转指令
class FunctionTracer {
public:
    explicit FunctionTracer(void* ptr)
        : m_ptr(ptr) {
        printIndent();
        std::cout << "Entering " << getClassName() << std::endl;
        indentLevel++;
    }

    ~FunctionTracer() {
        indentLevel--;
        printIndent();
        std::cout << "Exiting " << getClassName() << std::endl;
    }

private:
    void* m_ptr;
    static int indentLevel;
    void printIndent() const {
        for (int i = 0; i < indentLevel; ++i) {
            std::cout << "  ";  
        }
    }
    std::string getClassName() const {
        return typeid(*static_cast<Node*>(m_ptr)).name(); 
    }
};
int FunctionTracer::indentLevel = 0;

bool funcReturned = false;
Type* returnType = nullptr;
Node::Node()
{
    seq = counter++;
}

void Node::backPatch(std::vector<Instruction *> &list, BasicBlock *bb)
{
    for (auto &inst : list)
    {
        if (inst->isCond())
            dynamic_cast<CondBrInstruction *>(inst)->setTrueBranch(bb);
        else if (inst->isUncond())
        {
            dynamic_cast<UncondBrInstruction *>(inst)->setBranch(bb);
        }
    }
}

std::vector<Instruction *> Node::merge(std::vector<Instruction *> &list1, std::vector<Instruction *> &list2)
{
    std::vector<Instruction *> res(list1);
    res.insert(res.end(), list2.begin(), list2.end());
    return res;
}

void Ast::genCode(Unit *unit)
{
    std::cout << "Entering Ast::genCode" << std::endl;
    IRBuilder *builder = new IRBuilder(unit);
    Node::setIRBuilder(builder);
    root->genCode();
}

void BinaryExpr::genCode()
{
    FunctionTracer tracer(this);
    //std::cout << "Entering BinaryExpr::genCode" << std::endl;
    BasicBlock *bb = builder->getInsertBB();
    Function *func = bb->getParent();

    if (op == AND)
    {
        BasicBlock *trueBB = new BasicBlock(func); // if the result of lhs is true, jump to the trueBB.
        genBr = 1;
        expr1->genCode();
        backPatch(expr1->trueList(), trueBB);
        builder->setInsertBB(trueBB); // set the insert point to the trueBB so that intructions generated by expr2 will be inserted into it.
        expr2->genCode();
        true_list = expr2->trueList();
        false_list = merge(expr1->falseList(), expr2->falseList());
    }
    else if (op == OR)
    {
        // TODO: 实现 OR 操作符的逻辑
        BasicBlock *falseBB = new BasicBlock(func); // if the result of lhs is false, jump to the falseBB.
        genBr = 1;
        expr1->genCode();
        backPatch(expr1->falseList(), falseBB);
        builder->setInsertBB(falseBB); // set the insert point to the falseBB so that instructions generated by expr2 will be inserted into it.
        expr2->genCode();
        true_list = merge(expr1->trueList(), expr2->trueList());
        false_list = expr2->falseList();
    }
    else if (op >= LESS && op <= NEQ)
    {
        // TODO: 实现关系操作符 (LESS, GREATER, LEQ, GEQ, EQ, NEQ) 的逻辑
        genBr--;
        expr1->genCode();
        expr2->genCode();
        genBr++;

        int opcode = -1;
        switch (op)
        {
        case LESS:
            opcode = CmpInstruction::L;
            break;
        case LEQ:
            opcode = CmpInstruction::LE;
            break;
        case GREATER:
            opcode = CmpInstruction::G;
            break;
        case GEQ:
            opcode = CmpInstruction::GE;
            break;
        case EQ:
            opcode = CmpInstruction::E;
            break;
        case NEQ:
            opcode = CmpInstruction::NE;
            break;
        }
        new CmpInstruction(opcode, dst, expr1->getOperand(), expr2->getOperand(), bb);

        if (genBr > 0)
        {
            // 跳转目标block
            BasicBlock *trueBlock, *falseBlock, *mergeBlock;
            trueBlock = new BasicBlock(func);
            falseBlock = new BasicBlock(func);
            mergeBlock = new BasicBlock(func);
            true_list.push_back(new CondBrInstruction(trueBlock, falseBlock, dst, bb));
            false_list.push_back(new UncondBrInstruction(mergeBlock, falseBlock));
        }
    }
    else if (op >= ADD && op <= MOD)
    {
        expr1->genCode();
        expr2->genCode();
        Operand *src1 = expr1->getOperand();
        Operand *src2 = expr2->getOperand();
        int opcode;
        switch (op)
        {
        case ADD:
            opcode = BinaryInstruction::ADD;
            break;
        case SUB:
            opcode = BinaryInstruction::SUB;
            break;
        case MUL:
            opcode = BinaryInstruction::MUL;
            break;
        case DIV:
            opcode = BinaryInstruction::DIV;
            break;
        case MOD:
            opcode = BinaryInstruction::MOD;
            break;
        default:
            opcode = -1;
            break;
        }
        new BinaryInstruction(opcode, dst, src1, src2, bb);
    }
}

void Constant::genCode()
{
    FunctionTracer tracer(this);
    // we don't need to generate code.
}

void Id::genCode()
{
    //std::cout << "Entering genCode::genCode" << std::endl;
    if(getType()->isConst() && !getType()->isArray()){
        return;
    }
    BasicBlock *bb = builder->getInsertBB();
    Operand *addr = dynamic_cast<IdentifierSymbolEntry*>(symbolEntry)->getAddr();
    dst = new Operand(new TemporarySymbolEntry(dst->getType(), SymbolTable::getLabel()));
    if(getType()->isArray()){
        Operand* offset = nullptr;
        if(indices!=nullptr){
            indices->genCode();
            offset = indices->exprList[0]->getOperand();
        }
        std::vector<int> dimensions;
        if(getType()->isIntArray()){
            dimensions = dynamic_cast<IntArrayType*>(getType())->getDimensions();
        }
        else if(getType()->isConstIntArray()) {
            dimensions = dynamic_cast<ConstIntArrayType*>(getType())->getDimensions();
        }
        else if(getType()->isFloatArray()){
            dimensions = dynamic_cast<FloatArrayType*>(getType())->getDimensions();
        }
        else {
            dimensions = dynamic_cast<ConstFloatArrayType*>(getType())->getDimensions();
        }
        //如果是函数参数传入的数组指针，其最后一个维度为-1
        //此时需要生成新的load指令获取其地址
        if(dimensions[0]==-1){
            // printf("%d\n", dimensions[1]);
            TemporarySymbolEntry* se = new TemporarySymbolEntry(getType(), SymbolTable::getLabel());
            Operand* new_addr = new Operand(se);
            new LoadInstruction(new_addr, addr, bb);
            addr = new_addr;
        }
        for(unsigned int i = 1; indices!=nullptr && i < indices->exprList.size(); i++) {
            Operand* dim_i = new Operand(new ConstantSymbolEntry(TypeSystem::constIntType, dimensions[i]));
            TemporarySymbolEntry* se1 = new TemporarySymbolEntry(TypeSystem::intType, SymbolTable::getLabel());
            Operand* offset1 = new Operand(se1);
            new BinaryInstruction(BinaryInstruction::MUL, offset1, offset, dim_i, bb);  //offset1 = offset * dimensions[i]
            TemporarySymbolEntry* se2 = new TemporarySymbolEntry(TypeSystem::intType, SymbolTable::getLabel());
            offset = new Operand(se2);
            new BinaryInstruction(BinaryInstruction::ADD, offset, offset1, indices->exprList[i]->getOperand(), bb); //offset = offset1 + indices[i]
        }
        //索引维度<总维度，需要再乘一次最后的维度
        if(indices!=nullptr && indices->exprList.size()<dimensions.size()){
            Operand* dim_i = new Operand(new ConstantSymbolEntry(TypeSystem::constIntType, dimensions[indices->exprList.size()]));
            TemporarySymbolEntry* se1 = new TemporarySymbolEntry(TypeSystem::intType, SymbolTable::getLabel());
            Operand* offset1 = new Operand(se1);
            new BinaryInstruction(BinaryInstruction::MUL, offset1, offset, dim_i, bb);  //offset1 = offset * dimensions[i]
            offset = offset1;
        }
        Operand* offset1 = nullptr;
        if(indices!=nullptr){
            TemporarySymbolEntry* se1 = new TemporarySymbolEntry(TypeSystem::intType, SymbolTable::getLabel());
            offset1 = new Operand(se1);
            Operand* align = new Operand(new ConstantSymbolEntry(TypeSystem::constIntType, 4));
            new BinaryInstruction(BinaryInstruction::MUL, offset1, offset, align, bb);  //offset1 = offset * 4
        }
        else{
            offset1 = new Operand(new ConstantSymbolEntry(TypeSystem::constIntType, 0));
        }
        TemporarySymbolEntry* se2 = new TemporarySymbolEntry(getType(), SymbolTable::getLabel());
        Operand* offset_final = new Operand(se2);
        // 全局变量地址标签不能直接参与运算，需要先load
        if(dynamic_cast<IdentifierSymbolEntry*>(getSymbolEntry())->isGlobal()){
            TemporarySymbolEntry* se3 = new TemporarySymbolEntry(getType(), SymbolTable::getLabel());
            Operand* new_addr = new Operand(se3);
            new LoadInstruction(new_addr, addr, bb);
            addr = new_addr;
            se2->setGlobalArray();
            dynamic_cast<TemporarySymbolEntry*>(dst->getEntry())->setGlobalArray();
        }
        if(indices!=nullptr && indices->exprList.size()==dimensions.size()){
            new BinaryInstruction(BinaryInstruction::ADD, offset_final, offset1, addr, bb);  //offset_final = offset1 + addr
            // printf("%s\n", getSymbolEntry()->toStr().c_str());
            //进入此分支表明已经寻址完成，可以由array type转为普通type
            if(dst->getType()->isFloatArray() || dst->getType()->isConstFloatArray()){
                dst->getEntry()->setType(new FloatType(4));
                // 如果不是全局变量 那么就设置 need_fp 标志位
                if(!dynamic_cast<IdentifierSymbolEntry*>(getSymbolEntry())->isGlobal() && dimensions[0] != -1){
                    dynamic_cast<FloatType*>(dst->getEntry()->getType())->setNeedFP(true);
                }
            }
            new LoadInstruction(dst, offset_final, bb);
        }
        else{
            //为区分数组指针和数组值，需要置位dst的type中的pointer
            if(dst->getType()->isIntArray()){
                dst->getEntry()->setType(new IntArrayType(*(dynamic_cast<IntArrayType*>(dst->getType()))));
                dynamic_cast<IntArrayType*>(dst->getType())->setPointer(true);
            }
            else if(dst->getType()->isConstIntArray()){
                dst->getEntry()->setType(new ConstIntArrayType(*(dynamic_cast<ConstIntArrayType*>(dst->getType()))));
                dynamic_cast<ConstIntArrayType*>(dst->getType())->setPointer(true);
            }
            else if(dst->getType()->isFloatArray()){
                dst->getEntry()->setType(new FloatArrayType(*(dynamic_cast<FloatArrayType*>(dst->getType()))));
                dynamic_cast<FloatArrayType*>(dst->getType())->setPointer(true);
            }
            else if(dst->getType()->isConstFloatArray()){
                dst->getEntry()->setType(new ConstFloatArrayType(*(dynamic_cast<ConstFloatArrayType*>(dst->getType()))));
                dynamic_cast<ConstFloatArrayType*>(dst->getType())->setPointer(true);
            }
            new BinaryInstruction(BinaryInstruction::ADD, dst, offset1, addr, bb); 
        }
    }
    else{
        new LoadInstruction(dst, addr, bb);
    }
}

void IfStmt::genCode()
{
    FunctionTracer tracer(this);
    //std::cout << "Entering IfStmt::genCode" << std::endl;
    Function *func;
    BasicBlock *then_bb, *end_bb;

    func = builder->getInsertBB()->getParent();
    then_bb = new BasicBlock(func);
    end_bb = new BasicBlock(func);

    genBr = 1;
    cond->genCode();
    backPatch(cond->trueList(), then_bb);
    backPatch(cond->falseList(), end_bb);

    builder->setInsertBB(then_bb);
    thenStmt->genCode();
    then_bb = builder->getInsertBB();
    new UncondBrInstruction(end_bb, then_bb);

    builder->setInsertBB(end_bb);
}

void IfElseStmt::genCode()
{
    FunctionTracer tracer(this);
    // TODO: 实现 IfElse 语句的代码生成逻辑
    //std::cout << "Entering IfElseStmt::genCode" << std::endl;
    Function *func;
    BasicBlock *then_bb, *else_bb, *end_bb;

    func = builder->getInsertBB()->getParent();
    then_bb = new BasicBlock(func);
    else_bb = new BasicBlock(func);
    end_bb = new BasicBlock(func);

    genBr = 1;
    cond->genCode();
    backPatch(cond->trueList(), then_bb);
    backPatch(cond->falseList(), else_bb);

    // 先处理then分支
    builder->setInsertBB(then_bb);
    thenStmt->genCode();
    then_bb = builder->getInsertBB();
    new UncondBrInstruction(end_bb, then_bb);

    // 再处理else分支
    builder->setInsertBB(else_bb);
    elseStmt->genCode();
    else_bb = builder->getInsertBB();
    new UncondBrInstruction(end_bb, else_bb);

    builder->setInsertBB(end_bb);
}

void CompoundStmt::genCode()
{
    FunctionTracer tracer(this);
    // TODO: 实现复合语句的代码生成逻辑
    stmt->genCode();
}

void SeqNode::genCode()
{
    FunctionTracer tracer(this);
    // TODO: 实现序列节点的代码生成逻辑
    for (auto stmt : stmtList)
    {
        stmt->genCode();
    }
}

void DeclStmt::genCode()
{
    FunctionTracer tracer(this);
    for (auto stmt : defList)
    {
        stmt->genCode();
    }
}

void DefNode::genCode()
{
    FunctionTracer tracer(this);
      Operand *addr;
    IdentifierSymbolEntry *se = dynamic_cast<IdentifierSymbolEntry *>(id->getSymPtr());
    if (se->isGlobal())
    {
        SymbolEntry *addr_se;
        addr_se = new IdentifierSymbolEntry(*se);
        addr_se->setType(new PointerType(se->getType()));
        addr = new Operand(addr_se);
        se->setAddr(addr);
        this->builder->getUnit()->insertDecl(se);
    }
    else
    {
        Function *func = builder->getInsertBB()->getParent();
        BasicBlock *entry = func->getEntry();
        Instruction *alloca;
        SymbolEntry *addr_se;
        Type *type;
        type = new PointerType(se->getType());
        addr_se = new TemporarySymbolEntry(type, SymbolTable::getLabel());
        addr = new Operand(addr_se);
        alloca = new AllocaInstruction(addr, se); // allocate space for local id in function stack.
        entry->insertFront(alloca);               // allocate instructions should be inserted into the begin of the entry block.
        se->setAddr(addr);                        // set the addr operand in symbol entry so that we can use it in subsequent code generation.
    }
}

void AssignStmt::genCode()
{
    FunctionTracer tracer(this);
    BasicBlock *bb = builder->getInsertBB();
    Operand *addr = dynamic_cast<IdentifierSymbolEntry *>(lval->getSymPtr())->getAddr();
    expr->genCode();
    Operand *src = expr->getOperand();
    if(lval->getType()->isArray()) {
        ExprStmtNode* indices = dynamic_cast<Id*>(lval)->getIndices();
        indices->genCode();
        Operand* offset = indices->exprList[0]->getOperand();
        std::vector<int> dimensions;
        if(lval->getType()->isIntArray()){
            dimensions = dynamic_cast<IntArrayType*>(lval->getType())->getDimensions();
        }
        else{
            dimensions = dynamic_cast<FloatArrayType*>(lval->getType())->getDimensions();
        }
        //如果是函数参数传入的数组指针，其最后一个维度为-1
        //此时需要生成新的load指令获取其地址
        if(dimensions[dimensions.size()-1]==-1){
            TemporarySymbolEntry* se = new TemporarySymbolEntry(lval->getType(), SymbolTable::getLabel());
            Operand* new_addr = new Operand(se);
            new LoadInstruction(new_addr, addr, bb);
            addr = new_addr;
        }
        for(unsigned int i = 1; i < indices->exprList.size(); i++) {
            Operand* dim_i = new Operand(new ConstantSymbolEntry(TypeSystem::constIntType, dimensions[i]));
            TemporarySymbolEntry* se1 = new TemporarySymbolEntry(TypeSystem::intType, SymbolTable::getLabel());
            Operand* offset1 = new Operand(se1);
            new BinaryInstruction(BinaryInstruction::MUL, offset1, offset, dim_i, bb);  //offset1 = offset * dimensions[i]
            TemporarySymbolEntry* se2 = new TemporarySymbolEntry(TypeSystem::intType, SymbolTable::getLabel());
            offset = new Operand(se2);
            new BinaryInstruction(BinaryInstruction::ADD, offset, offset1, indices->exprList[i]->getOperand(), bb); //offset = offset1 + indices[i]
        }
        TemporarySymbolEntry* se1 = new TemporarySymbolEntry(TypeSystem::intType, SymbolTable::getLabel());
        Operand* offset1 = new Operand(se1);
        Operand* align = new Operand(new ConstantSymbolEntry(TypeSystem::constIntType, 4));
        new BinaryInstruction(BinaryInstruction::MUL, offset1, offset, align, bb);  //offset1 = offset * 4
        TemporarySymbolEntry* se2 = new TemporarySymbolEntry(lval->getType(), SymbolTable::getLabel());
        Operand* offset_final = new Operand(se2);
        // 全局变量地址标签不能直接参与运算，需要先load
        if(dynamic_cast<IdentifierSymbolEntry*>(dynamic_cast<Id*>(lval)->getSymbolEntry())->isGlobal()){
            TemporarySymbolEntry* se3 = new TemporarySymbolEntry(lval->getType(), SymbolTable::getLabel());
            Operand* new_addr = new Operand(se3);
            new LoadInstruction(new_addr, addr, bb);
            addr = new_addr;
            se2->setGlobalArray();
        }
        new BinaryInstruction(BinaryInstruction::ADD, offset_final, offset1, addr, bb);  //offset_final = offset1 + addr
        new StoreInstruction(offset_final, src, bb);
    }
    else {
        new StoreInstruction(addr, src, bb);
    }
    
}

void WhileStmt::genCode()
{
    FunctionTracer tracer(this);
    whileStack.push(this);

    Function *func = builder->getInsertBB()->getParent();
    BasicBlock *bb = builder->getInsertBB();

    stmt_bb = new BasicBlock(func);
    cond_bb = new BasicBlock(func);
    end_bb = new BasicBlock(func);

    new UncondBrInstruction(cond_bb, bb);

    builder->setInsertBB(cond_bb);
    genBr=1;
    Cond->genCode();
    backPatch(Cond->trueList(), stmt_bb);
    backPatch(Cond->falseList(), end_bb);

    builder->setInsertBB(stmt_bb);
    stmt->genCode();
    bb = builder->getInsertBB();
    new UncondBrInstruction(cond_bb, bb);

    builder->setInsertBB(end_bb);

    whileStack.pop();
}

void ContinueStmt::genCode()
{
    FunctionTracer tracer(this);
    Function *func = builder->getInsertBB()->getParent();
    BasicBlock *bb = builder->getInsertBB();

    BasicBlock* condbb = ((WhileStmt*)whileStmt)->getCondBB();

    new UncondBrInstruction(condbb, bb); // 跳转到循环条件语句块

    BasicBlock *nextBlock = new BasicBlock(func);
    builder->setInsertBB(nextBlock);
}

void BreakStmt::genCode()
{
    FunctionTracer tracer(this);
    Function *func = builder->getInsertBB()->getParent();
    BasicBlock *bb = builder->getInsertBB();

    BasicBlock *endbb = ((WhileStmt *)whileStack.top())->getEndBB();

    new UncondBrInstruction(endbb, bb); // 跳转到循环结束语句块
    BasicBlock *next_bb = new BasicBlock(func);
    builder->setInsertBB(next_bb);
}

void ReturnStmt::genCode()
{
    FunctionTracer tracer(this);
    BasicBlock *bb = builder->getInsertBB();
    if (retValue)
    {
        retValue->genCode();
        Operand *operand = retValue->getOperand();
        new RetInstruction(operand, bb);
    }
    else
    {
        new RetInstruction(nullptr, bb);
    }
}

void ForStmt::genCode()
{
    FunctionTracer tracer(this);
    forStack.push(this);
    Function *func = builder->getInsertBB()->getParent();
    BasicBlock *bb=builder->getInsertBB();
    
    init_bb = new BasicBlock(func);
    cond_bb = new BasicBlock(func);
    loop_bb = new BasicBlock(func);
    end_bb = new BasicBlock(func);
    stmt_bb = new BasicBlock(func);

    new UncondBrInstruction(init_bb, bb);

    builder->setInsertBB(init_bb);
    initStmt->genCode();
    new UncondBrInstruction(cond_bb, init_bb);

    builder->setInsertBB(cond_bb);
    genBr = 1;
    Cond->genCode();
    backPatch(Cond->trueList(), stmt_bb);
    backPatch(Cond->falseList(), end_bb);

    builder->setInsertBB(stmt_bb);
    stmt->genCode();
    stmt_bb = builder->getInsertBB();
    new UncondBrInstruction(loop_bb, stmt_bb);

    builder->setInsertBB(loop_bb);
    loopStmt->genCode();
    new UncondBrInstruction(cond_bb, loop_bb);

    builder->setInsertBB(end_bb);

    forStack.pop();

}

void IOStmt::genCode()
{
    FunctionTracer tracer(this);
    BasicBlock *bb = builder->getInsertBB();
    if (op == PRINT)
    {
        expr->genCode();
        Operand *src = expr->getOperand();
        new PrintInstruction(src, bb);
    }
    else if (op == SCAN)
    {
        Operand *addr = dynamic_cast<IdentifierSymbolEntry *>(expr->getSymPtr())->getAddr();
        new ScanInstruction(addr, bb);
    }
}

// main function
void FunctionDef::genCode()
{
    FunctionTracer tracer(this);
    Unit *unit = builder->getUnit();
    Function *func = new Function(unit, se);
    BasicBlock *entry = func->getEntry();
    // set the insert point to the entry basicblock of this function.
    builder->setInsertBB(entry);

    stmt->genCode();

    /**
     * Construct control flow graph. You need do set successors and predecessors for each basic block.
     * Todo
     */
    // 遍历Function中所有的BasicBlock，在各个BasicBlock之间建立控制流关系
    for (auto block = func->begin(); block != func->end(); block++)
    {
        //std::cout<<"block->output()"<<*block<<std::endl;
        //(*block)->output();
        if((*block)->empty())
        {
           std::cout<<"block is empty"<<std::endl;
        }
        // 清除ret之后的全部指令
        Instruction *index = (*block)->begin();
        while (index != (*block)->end())
        {
            if (index->isRet())
            {
                while (index != (*block)->rbegin())
                {
                    (*block)->remove(index->getNext());
                }
                break;
            }
            index = index->getNext();
        }
        Instruction *last = (*block)->rbegin();
        if (last->isCond())
        {
            BasicBlock *trueBlock = dynamic_cast<CondBrInstruction *>(last)->getTrueBranch();
            BasicBlock *falseBlock = dynamic_cast<CondBrInstruction *>(last)->getFalseBranch();
            (*block)->addSucc(trueBlock);
            (*block)->addSucc(falseBlock);
            trueBlock->addPred(*block);
            falseBlock->addPred(*block);
        }
        if (last->isUncond())
        {
            BasicBlock *dstBlock = dynamic_cast<UncondBrInstruction *>(last)->getBranch();
            (*block)->addSucc(dstBlock);
            dstBlock->addPred(*block);
        }
    }

}

void Ast::typeCheck(Node **recursive)
{
    // TODO: 实现抽象语法树的类型检查逻辑
    if (root != nullptr)
        root->typeCheck(nullptr);
    printf("Type Check End!\n");
}

void BinaryExpr::typeCheck(Node **recursive)
{
    // TODO: 实现二元表达式的类型检查逻辑

    expr1->typeCheck((Node **)&(this->expr1));
    if(expr2 != nullptr)
        expr2->typeCheck((Node **)&(this->expr2));
    else
        return;
    Type *expr1_type = expr1->getSymPtr()->getType();
    Type *expr2_type = expr2->getSymPtr()->getType();
    // bool isVoidType(const Type* expr_type) {
    // return expr_type->toStr() == "void()";
    // }

    if (expr1_type->toStr() == "void()") {
        fprintf(stderr, " empty type %s can not assignment!",
                expr1_type->toStr().c_str());
        exit(EXIT_FAILURE);
        return;
    }
    else{
        if(expr2_type->toStr() == "void()"){
        fprintf(stderr, " empty type %s can not assignment!",
                expr2_type->toStr().c_str());
        exit(EXIT_FAILURE);
        return;
        }
    }

    if (expr1->getSymPtr()->isConstant() && expr2->getSymPtr()->isConstant())
    {
        int value1 = dynamic_cast<ConstantSymbolEntry *>(expr1->getSymPtr())->getValue();
        int value2 = dynamic_cast<ConstantSymbolEntry *>(expr2->getSymPtr())->getValue();
        int result = 0;
        switch (op)
        {
        case ADD:
            result = value1 + value2;
            break;
        case SUB:
            result = value1 - value2;
            break;
        case MUL:
            result = value1 * value2;
            break;
        case DIV:
            result = value1 / value2;
            break;
        case MOD:
            result = value1 % value2;
            break;
        case AND:
            result = value1 && value2;
            break;
        case OR:
            result = value1 || value2;
            break;
        case LESS:
            result = value1 < value2;
            break;
        case GREATER:
            result = value1 > value2;
            break;
        case EQ:
            result = value1 == value2;
            break;
        case NEQ:
            result = value1 != value2;
            break;
        case GEQ:
            result = value1 >= value2;
            break;
        case LEQ:
            result = value1 <= value2;
            break;
        }
        SymbolEntry *se = new ConstantSymbolEntry(TypeSystem::intType, result);
        Constant *newNode = new Constant(se);
        *recursive = (Node *)newNode;
    }
}

void Constant::typeCheck(Node **recursive)
{
    // TODO: 实现常量的类型检查逻辑
}

void Id::typeCheck(Node** parentToChild)
{
    // 如果是一个普通变量就什么也不做
    // 如果是一个普通常量
    if(!isArray() && symbolEntry->getType()->isConst() && parentToChild != nullptr) {
        ConstantSymbolEntry* newConst = new ConstantSymbolEntry(symbolEntry->getType(), dynamic_cast<IdentifierSymbolEntry*>(symbolEntry)->value);
        Constant* newNode = new Constant(newConst);
        (*parentToChild) = newNode;
    }
    // 如果是数组 要看看维度信息有没有初始化
    // 由于在语法解析阶段已经判断了标识符先定义再使用
    // 所以如果维度信息还未初始化则说明当前是数组定义阶段
    if(isArray() && indices!=nullptr){
        indices->typeCheck(nullptr);
        // 检查indices下的exprList(私有域)中的每个exprNode的类型，若不为自然数则报错
        // if(((IdentifierSymbolEntry*)getSymPtr())->arrayDimension.empty()){
        if((getType()->isIntArray() && dynamic_cast<IntArrayType*>(getType())->getDimensions().empty()) ||
            (getType()->isConstIntArray() && dynamic_cast<ConstIntArrayType*>(getType())->getDimensions().empty()) ||
            (getType()->isFloatArray() && dynamic_cast<FloatArrayType*>(getType())->getDimensions().empty()) ||
            (getType()->isConstFloatArray() && dynamic_cast<ConstFloatArrayType*>(getType())->getDimensions().empty())){
            // (getType()->isIntArray() && dynamic_cast<IntArrayType*>(getType())->getDimensions().back()==-1)){
            indices->initDimInSymTable((IdentifierSymbolEntry*)getSymPtr());
        }
        // 读取常量数组 这个不打算做了
        else if(getType()->isConst()){
            //TODO: 将常量数组+全常量下标的数组元素访问替换为字面值常量节点Constant
            //STEP：1.遍历indices下的exprList(私有域)，查看是否有非常量节点。若有，直接返回
            //STEP: 2.若全部为常量下标，替换
        }
    }
}


void IfStmt::typeCheck(Node **recursive)
{
    // TODO: 实现 if 语句的类型检查逻辑
    cond->typeCheck((Node **)&(this->cond));
    if (cond->getSymPtr()->getType()->isInt())
        cond->getSymPtr()->setType(TypeSystem::boolType);
    else{
        if (cond->getSymPtr()->getType()->isFunc()){
            FunctionType *temp = static_cast<FunctionType *>(cond->getSymPtr()->getType());
            if (temp->getRetType()->isInt()){
                cond->getSymPtr()->setType(TypeSystem::boolType);
                thenStmt->typeCheck(nullptr);
                return;
            }
        }
        fprintf(stderr, "if条件类型不匹配\n");
        exit(EXIT_FAILURE);
        return;
    }
}

void IfElseStmt::typeCheck(Node **recursive)
{
    // TODO: 实现 if-else 语句的类型检查逻辑
    cond->typeCheck((Node **)&(this->cond));
    if (cond->getSymPtr()->getType()->isInt())
        cond->getSymPtr()->setType(TypeSystem::boolType);
    else{
        if (cond->getSymPtr()->getType()->isFunc()){
            FunctionType *temp = static_cast<FunctionType *>(cond->getSymPtr()->getType());
            if (temp->getRetType()->isInt()){
                cond->getSymPtr()->setType(TypeSystem::boolType);
                thenStmt->typeCheck((Node **)&(this->thenStmt));
                elseStmt->typeCheck((Node **)&(this->thenStmt));
                return;
            }
        }
        fprintf(stderr, "if-else条件类型不匹配\n");
        exit(EXIT_FAILURE);
        return;
    }
    if (thenStmt != nullptr)
        thenStmt->typeCheck((Node **)&(this->thenStmt));
    else
        thenStmt = nullptr;
}

void CompoundStmt::typeCheck(Node **recursive)
{
    // TODO: 实现复合语句的类型检查逻辑
    if (stmt != NULL)
    {
        stmt->typeCheck(nullptr);
    }
}

void SeqNode::typeCheck(Node **recursive)
{
    // TODO: 实现序列节点的类型检查逻辑
    for (int i = 0; i < (int)stmtList.size(); i++)
    {
        stmtList[i]->typeCheck((Node **)&(stmtList[i]));
    }
}

void DeclStmt::typeCheck(Node **recursive)
{
    // TODO: 实现声明语句的类型检查逻辑
    for (int i = 0; i < (int)defList.size(); i++)
    {
        defList[i]->typeCheck(nullptr);
    }
}

void DefNode::typeCheck(Node **recursive)
{
   id->typeCheck(nullptr);
    // 不赋初值，直接返回
    if(initVal==nullptr){
        return;
    }

    if(id->getType()->isArray()) {
        ArrayUtil::init();
        ArrayUtil::setArrayType(id->getType());
        initVal->typeCheck((Node**)&(initVal));
        this->initVal = new InitValNode(dynamic_cast<InitValNode*>(this->initVal)->isConst());
        std::vector<ExprNode*> initList = ArrayUtil::getInitVals();
        for(auto & child : initList){
            InitValNode* newNode = new InitValNode(dynamic_cast<InitValNode*>(this->initVal)->isConst());
            newNode->setLeafNode(child);
            dynamic_cast<InitValNode*>(this->initVal)->addNext(newNode);
        }
    }
    else {
        initVal->typeCheck((Node**)&(initVal));
    }


    if(!id->getType()->isArray()){//不是数组时，右边可能出现函数：int a = f();
        if(((ExprNode*)initVal)->getType()->isFunc() && 
            (!((FunctionType*)(((ExprNode*)initVal)->getType()))->getRetType()->calculatable())){//右边是个为返回值空的函数
            fprintf(stderr, "expected a return value, but functionType %s return nothing\n", ((ExprNode*)initVal)->getType()->toStr().c_str());
            exit(EXIT_FAILURE);
        }
    }
    if(id->getType()->isConst()){
        // 判断是否用变量给常量赋值
        if(!isArray) {
            if(!((ExprNode*)initVal)->getType()->isConst()) {
                fprintf(stderr, "attempt to initialize variable value to const\n");
                exit(EXIT_FAILURE);
            }
        }
        else{
            if(!((InitValNode*)initVal)->isConst()) {
                fprintf(stderr, "attempt to initialize variable value to const\n");
                exit(EXIT_FAILURE);
            }
        }
        // 接下来就是常量计算的工作了
        // 数组初始化值 暂时不打算做了
        if(id->getType()->isArray()){
            IdentifierSymbolEntry* se = (IdentifierSymbolEntry*)id->getSymPtr();
            for(auto val : dynamic_cast<InitValNode*>(initVal)->getInnerList()) {
                ExprNode* leafNode = val->getLeafNode();
                double value= ((ConstantSymbolEntry*)((ExprNode*)leafNode)->getSymPtr())->getValue();
                se->arrayValues.push_back(value);
            }
        }
        // 常量初始化值
        else{
            IdentifierSymbolEntry* se = (IdentifierSymbolEntry*)id->getSymPtr();
            se->value = ((ConstantSymbolEntry*)((ExprNode*)initVal)->getSymPtr())->getValue();
        }   
    }
    // 如果是全局变量，也要根据需要赋值
    if(dynamic_cast<IdentifierSymbolEntry*>(id->getSymPtr())->isGlobal()) {
        // 对于初始化值不为空的，要进行初始化赋值
        if(initVal != nullptr) {
            // 只允许使用常量对全局变量进行赋值
//            if(!((ExprNode*)initVal)->getType()->isConst()) {
//                fprintf(stderr, "not allow to initialize global variable with not const value\n");
//                exit(EXIT_FAILURE);
//            }
            IdentifierSymbolEntry* se = (IdentifierSymbolEntry*)id->getSymPtr();
            if(!se->getType()->isArray()) {
                se->value = ((ConstantSymbolEntry*)((ExprNode*)initVal)->getSymPtr())->getValue();
            }
            else {
                if(se->arrayValues.empty()) {
                    for(auto val : dynamic_cast<InitValNode*>(initVal)->getInnerList()) {
                        ExprNode* leafNode = val->getLeafNode();
                        double value= ((ConstantSymbolEntry*)((ExprNode*)leafNode)->getSymPtr())->getValue();
                        se->arrayValues.push_back(value);
                    }
                }
            }
        }
    }
}

void ContinueStmt::typeCheck(Node **recursive)
{
}

void BreakStmt::typeCheck(Node **recursive)
{
}

void ReturnStmt::typeCheck(Node **recursive)
{
    // TODO: 实现返回语句的添加类型检查逻辑
    if(!returnType){
        fprintf(stderr, "return statement outside functions\n");
        exit(EXIT_FAILURE);
    }
    else if(returnType->isVoid() && retValue!=nullptr){
        fprintf(stderr, "value returned in a void() function\n");
        exit(EXIT_FAILURE);
    }
    else if(!returnType->isVoid() && retValue==nullptr){
        fprintf(stderr, "expected a %s type to return, but returned nothing\n", returnType->toStr().c_str());
        exit(EXIT_FAILURE);
    }
    if(!returnType->isVoid()){
        retValue->typeCheck((Node**)&(retValue));
    }
    this->retType = returnType;
    funcReturned = true;
}

void AssignStmt::typeCheck(Node **recursive)
{
    // TODO: 实现赋值语句的类型检查逻辑
    lval->typeCheck(nullptr);
    expr->typeCheck((Node**)&(this->expr));
    if(lval->getType()->isConst()) {
        fprintf(stderr, "Unable to assign value to const variable %s\n", lval->getSymPtr()->toStr().c_str());
        exit(EXIT_FAILURE);
    }
    if(expr->getType()->isFunc() && ((FunctionType*)(expr->getType()))->getRetType()->isVoid()){//返回值为void的函数做运算数
        fprintf(stderr, "expected a return value, but functionType %s returns nothing\n", expr->getType()->toStr().c_str());
        exit(EXIT_FAILURE);
    }
}

void WhileStmt::typeCheck(Node **recursive)
{
    // 1判断cond的类型 必须要是INT的，并设置cond为bool
    if (Cond->getSymPtr()->getType()->isInt())
        Cond->getSymPtr()->setType(TypeSystem::boolType);
    else{
        fprintf(stderr, "condition in while don`t match\n");
        exit(EXIT_FAILURE);
        return;
    }
    // 对函数体进行类型检查
    stmt->typeCheck(nullptr);
}

void FunctionDef::typeCheck(Node **recursive)
{
    // 获取函数的返回值类型
    returnType = ((FunctionType *)se->getType())->getRetType();
    funcReturned = false;
    stmt->typeCheck(nullptr);
    if (!funcReturned && !returnType->isVoid()){
        fprintf(stderr, "expected a %s type to return, but no returned value found\n", returnType->toStr().c_str());
        exit(EXIT_FAILURE);
    }
    returnType = nullptr;

}

void IOStmt::typeCheck(Node **recursive)
{

}

void ForStmt::typeCheck(Node **recursive)
{
    
}

void BinaryExpr::output(int level)
{
    std::string op_str;
    switch (op)
    {
    case ADD:
        op_str = "add";
        break;
    case SUB:
        op_str = "sub";
        break;
    case MUL:
        op_str = "mul";
        break;
    case DIV:
        op_str = "div";
        break;
    case MOD:
        op_str = "mod";
        break;
    case AND:
        op_str = "and";
        break;
    case OR:
        op_str = "or";
        break;
    case LESS:
        op_str = "less";
        break;
    case GREATER:
        op_str = "greater";
        break;
    case EQ:
        op_str = "equ";
        break;
    case NEQ:
        op_str = "noequ";
        break;
    case GEQ:
        op_str = "larand";
        break;
    case LEQ:
        op_str = "lesand";
        break;
    case NOT:
        op_str = "not";
        break;
    }

    fprintf(yyout, "%*cBinaryExpr\top: %s\n", level, ' ', op_str.c_str());
    expr1->output(level + 4);
    if (expr2 != nullptr)
        expr2->output(level + 4);
}



void Ast::output()
{
    fprintf(yyout, "program\n");
    if (root != nullptr)
        root->output(4);
}

void Constant::output(int level)
{
    std::string type, value;
    type = symbolEntry->getType()->toStr();
    value = symbolEntry->toStr();
    fprintf(yyout, "%*cInteger\tvalue: %s\ttype: %s\n", level, ' ',
            value.c_str(), type.c_str());
}

void Id::output(int level)
{
    std::string name, type;
    int scope;
    name = symbolEntry->toStr();
    type = symbolEntry->getType()->toStr();
    scope = dynamic_cast<IdentifierSymbolEntry *>(symbolEntry)->getScope();
    fprintf(yyout, "%*cId\tname: %s\tscope: %d\ttype: %s\n", level, ' ',
            name.c_str(), scope, type.c_str());
}

void CompoundStmt::output(int level)
{
    fprintf(yyout, "%*cCompoundStmt\n", level, ' ');
    stmt->output(level + 4);
}

void SeqNode::addNext(StmtNode *next)
{
    stmtList.push_back(next);
}

void SeqNode::output(int level)
{
    fprintf(yyout, "%*cSequence\n", level, ' ');
    for (auto stmt : stmtList)
    {
        stmt->output(level + 4);
    }
}

void DeclStmt::addNext(DefNode *next)
{
    defList.push_back(next);
}

void DeclStmt::output(int level)
{
    fprintf(yyout, "%*cDeclStmt\n", level, ' ');
    for (auto def : defList)
    {
        def->output(level + 4);
    }
}

void DefNode::output(int level)
{

    fprintf(yyout, "%*cDefNoden\n", level, ' ');
    id->output(level + 4);
    if (initVal == nullptr)
    {
        fprintf(yyout, "%*cnull\n", level + 4, ' ');
    }
    else
    {
        initVal->output(level + 4);
    }
}

void IfStmt::output(int level)
{
    fprintf(yyout, "%*cIfStmt\n", level, ' ');
    cond->output(level + 4);
    thenStmt->output(level + 4);
}

void IfElseStmt::output(int level)
{
    fprintf(yyout, "%*cIfElseStmt\n", level, ' ');
    cond->output(level + 4);
    thenStmt->output(level + 4);
    elseStmt->output(level + 4);
}

void BreakStmt::output(int level)
{
    fprintf(yyout, "%*cBreakStmt\n", level, ' ');
}

void ContinueStmt::output(int level)
{
    fprintf(yyout, "%*cContinueStmt\n", level, ' ');
}

void ReturnStmt::output(int level)
{
    fprintf(yyout, "%*cReturnStmt\n", level, ' ');
    retValue->output(level + 4);
}

void AssignStmt::output(int level)
{
    fprintf(yyout, "%*cAssignStmt\n", level, ' ');
    lval->output(level + 4);
    expr->output(level + 4);
}

void WhileStmt::output(int level)
{
    fprintf(yyout, "%*cWhileStmt\n", level, ' ');
    Cond->output(level + 4);
    stmt->output(level + 4);
}

void ForStmt::output(int level)
{
    fprintf(yyout, "%*cForStmt\n", level, ' ');
    initStmt->output(level + 4);
    Cond->output(level + 4);
    loopStmt->output(level + 4);
    stmt->output(level + 4);
}

void IOStmt::output(int level)
{
    
    if (op == PRINT)
    {
        fprintf(yyout, "%*cIOStmt op: print\n", level, ' ');
    }
    else
    {
        fprintf(yyout, "%*cIOStmt op: scan\n", level, ' ');
    }
    expr->output(level + 4);
}

void FunctionDef::output(int level)
{
    std::string name, type;
    name = se->toStr();
    type = se->getType()->toStr();
    fprintf(yyout, "%*cFunctionDefine function name: %s, type: %s\n", level, ' ',
            name.c_str(), type.c_str());
    stmt->output(level + 4);

}

void InitValNode::genCode()
{
    // 如果是个叶节点
    if(this->leafNode != nullptr) {
        this->leafNode->genCode();
        Operand* src = leafNode->getOperand();
        int offset = ArrayUtil::getCurrentOffset() * 4;
        Operand* offset_operand = new Operand(new ConstantSymbolEntry(TypeSystem::constIntType, offset));
        Operand* final_offset = new Operand(new TemporarySymbolEntry(ArrayUtil::getArrayType(), SymbolTable::getLabel()));
        Operand* addr = ArrayUtil::getArrayAddr();
        // 计算最终地址偏移
        new BinaryInstruction(BinaryInstruction::ADD, final_offset, offset_operand, addr, builder->getInsertBB());
        // 插入 store 指令
        new StoreInstruction(final_offset, src, builder->getInsertBB());
    }
    // 经过 typecheck 之后 数组初始化值已经被全部展平
    for(auto child : innerList) {
        child->genCode();
        ArrayUtil::incCurrentOffset();
    }
}
void InitValNode::typeCheck(Node** parentToChild)
{
    ArrayUtil::incCurrentDim();
    bool padding = true;
    if(this->leafNode != nullptr) {
        this->leafNode->typeCheck((Node**)&(this->leafNode));
        ArrayUtil::insertInitVal(this->leafNode);
        padding = false;

    }
    // 首先对 innerList 进行递归
    int size = 0;
    for(auto & child : innerList){
        child->typeCheck((Node**)&child);
        size++;
    }
//    int padding = currentDimSize - (int)innerList.size();
    // 然后对当前维度进行填充
    if(padding) {
        ArrayUtil::paddingInitVal(size);
    }
    ArrayUtil::decCurrentDim();
}
void InitValNode::addNext(InitValNode* next)
{
    innerList.push_back(next);
}

void InitValNode::output(int level){
    std::string constStr = isconst ? "true" : "false";
    fprintf(yyout, "%*cInitValNode\tisConst:%s\n", level, ' ', constStr.c_str());
    for(auto child : innerList)
    {
        child->output(level+4);
    }
    if(leafNode!=nullptr){
        leafNode->output(level+4);
    }

}
void InitValNode::setLeafNode(ExprNode* leaf)
{
    leafNode = leaf;
}

bool InitValNode::isLeaf()
{
    return innerList.empty();
}

void ExprStmtNode:: addNext(ExprNode* next){exprList.push_back(next);};
void ExprStmtNode:: addFirst(ExprNode* first){exprList.insert(exprList.begin(), first);};
void ExprStmtNode:: output(int level){fprintf(yyout, "%*cExprStmtNode\n", level, ' ');
    for(auto expr : exprList)
    {
        expr->output(level+4);
    }};
void ExprStmtNode:: typeCheck(Node** parentToChild){for(int i = 0;i<(int)exprList.size();++i){
        exprList[i]->typeCheck((Node**)&(exprList[i]));
    }};
void ExprStmtNode:: genCode(){for(auto expr : exprList){
        expr->genCode();
    }};
void ExprStmtNode:: initDimInSymTable(IdentifierSymbolEntry* se){
    for(auto expr :exprList){
        // 既不是字面值常量，也不是常量表达式
        if(!(expr->getSymPtr()->isConstant() || expr->getType()->isConst())){
            fprintf(stderr, "array dimensions must be constant! %d %d\n", expr->getSymPtr()->isConstant(), expr->getType()->isConst());
            fprintf(stderr, "%d %d\n", (int)((ConstantSymbolEntry*)(expr->getSymPtr()))->getValue(), (int)((IdentifierSymbolEntry*)(expr->getSymPtr()))->value);
            exit(EXIT_FAILURE);
        }
        // 字面值常量，值存在ConstantSymbolEntry中
        if(expr->getSymPtr()->isConstant()){
            // se->arrayDimension.push_back((int)((ConstantSymbolEntry*)(expr->getSymPtr()))->getValue());
            if(se->getType()->isIntArray()){
                dynamic_cast<IntArrayType*>(se->getType())->pushBackDimension((int)((ConstantSymbolEntry*)(expr->getSymPtr()))->getValue());
            }
            else if(se->getType()->isConstIntArray()) {
                dynamic_cast<ConstIntArrayType*>(se->getType())->pushBackDimension((int)((ConstantSymbolEntry*)(expr->getSymPtr()))->getValue());
            }
            else if(se->getType()->isFloatArray()){
                dynamic_cast<FloatArrayType*>(se->getType())->pushBackDimension((int)((ConstantSymbolEntry*)(expr->getSymPtr()))->getValue());
            }
            else {
                dynamic_cast<ConstFloatArrayType*>(se->getType())->pushBackDimension((int)((ConstantSymbolEntry*)(expr->getSymPtr()))->getValue());
            }
        }
        // 常量表达式，值存在IdentifierSymbolEntry中
        else if(expr->getType()->isConst()){
            // se->arrayDimension.push_back((int)((IdentifierSymbolEntry*)(expr->getSymPtr()))->value);
            if(se->getType()->isIntArray()){
                dynamic_cast<IntArrayType*>(se->getType())->pushBackDimension((int)((IdentifierSymbolEntry*)(expr->getSymPtr()))->value);
            }
            else{
                dynamic_cast<FloatArrayType*>(se->getType())->pushBackDimension((int)((IdentifierSymbolEntry*)(expr->getSymPtr()))->value);
            }
        }
    }
};

Type* ExprNode::getType()
{
    return symbolEntry->getType();
}

void ExprNode::setType(Type* type)
{
    symbolEntry->setType(type);
}

bool Id::isArray()
{
    return getType()->isArray();
}